services:
  p4:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: novocert-p4:compose-build
    container_name: novocert-p4
    environment:
      - FDR_TYPE=peptide
      - FDR=0.01
    volumes:
      - type: bind
        source: ../test_data/4/t_d.pin
        target: /app/t_d.pin
      - type: bind
        source: ../test_data/4/output
        target: /app/output
