name: Auto Update Issue Title

on:
  issues:
    types: [opened]

jobs:
  update-issue-title:
    runs-on: ubuntu-latest
    steps:
      - name: Update issue title with author
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const author = issue.user.login;
            const currentTitle = issue.title;
            
            // 이미 작성자 이름이 포함되어 있는지 확인
            if (!currentTitle.includes(`[${author}]`)) {
              // 제목에서 태그 부분 추출
              const tagMatch = currentTitle.match(/^(\[.*?\])/);
              let newTitle;
              
              if (tagMatch) {
                // 태그가 있으면 태그 뒤에 작성자 추가
                const tag = tagMatch[1];
                const restOfTitle = currentTitle.substring(tagMatch[0].length).trim();
                newTitle = `${tag} [${author}] ${restOfTitle}`;
              } else {
                // 태그가 없으면 맨 앞에 작성자 추가
                newTitle = `[${author}] ${currentTitle}`;
              }
              
              // 이슈 제목 업데이트
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                title: newTitle
              });
              
              console.log(`Updated issue #${issue.number} title: "${currentTitle}" → "${newTitle}"`);
            } else {
              console.log(`Issue #${issue.number} already has author name in title`);
            } 